export const vehicleTypes = [
  "Small Economy",
  "Economy Sedan",
  "Mid-Size Sedan",
  "Compact Sedan",
  "Standard Sedan",
  "Full-Size Sedan",
  "Premium Sedan",
  "Luxury Sedan",
  "Compact SUV",
  "Mid-Size Hybrid SUV",
  "Intermediate SUV",
  "Premium Compact SUV",
  "Full-Size SUV",
  "Extraordinary Large SUV",
  "Standard MPV",
  "Full-Size MPV",
  "Premium MPV",
  "Compact Electric",
  "Compact Crossover Electric",
  "Mid-Size Crossover Electric",
  "Extraordinary Sport Electric",
  "Compact Station Wagon",
  "Mid-Size Station Wagon",
  "Full-Size Station Wagon",
  "Premium Station Wagon",
  "Cool Convertible",
  "Premium Convertible",
  "Extraordinary Convertible",
];
